num=int(input("enter a numberrrrrrrr"))
if num == 39:
    print("PIZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA")
else:
    print("NO PIZAAAAAAAAAAAAAAAAAA AWW MAN")